# ZAD1
#  zdanie=input("podaj zdanie \n")
#  print(zdanie.count(" ")) 



#liczba1,liczba2 = (int(input("podaj liczbe")),(int(input("podaj 2 liczbe"))))
#print(liczba2,liczba1)

 #Zad2 
# import sys 
# print("podaj liczby")
# l=int(sys.stdin.readline())
# l2=int(sys.stdin.readline())
# x=l*l2
# sys.stdout.write(str(x))


#ZAD3
#= == < > !=


#Zad4
# podana=int(input("podaj liczbe by wyciagnac bezwzgledna"))
# print("bezwzgledna",abs(podana))

#Zad5
a,b,c=(int(input("podajl liczbe 1")),int(input("podaj liczbe 2")), int(input("podaj liczbe 3")))